// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8gB8J7n0ddjO9A_EXX4YUSoAkiBIfpM0',
    appId: '1:975925187201:web:a809504caad65e6244f380',
    messagingSenderId: '975925187201',
    projectId: 'streamingapp-4b1a2',
    authDomain: 'streamingapp-4b1a2.firebaseapp.com',
    storageBucket: 'streamingapp-4b1a2.appspot.com',
    measurementId: 'G-MP9D8C6G25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbsyRdq6hK2UCklQIOLVrZFgFpVhvQe9U',
    appId: '1:975925187201:android:3ea31f3b442da70b44f380',
    messagingSenderId: '975925187201',
    projectId: 'streamingapp-4b1a2',
    storageBucket: 'streamingapp-4b1a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq1Mmm1Hy2zFTpQXpCdVqSRHeHnmRG4-M',
    appId: '1:975925187201:ios:bd000ea0fb76fe0c44f380',
    messagingSenderId: '975925187201',
    projectId: 'streamingapp-4b1a2',
    storageBucket: 'streamingapp-4b1a2.appspot.com',
    iosClientId:
        '975925187201-oq9qt6g9j2n2kkhnuvc7h08ikqc0pmq0.apps.googleusercontent.com',
    iosBundleId: 'site.tunckankilic.streamingapp',
  );
}
